name: ruby-core

on:
  pull_request:

  push:
    branches:
      - master

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  ruby_core:
    name: ${{matrix.target}} under a ruby-core / ${{matrix.branch}}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        target: [Rubygems, Bundler]
        branch: [ruby_3_4, ruby_4_0, master]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: ruby/ruby
          path: ruby/ruby
          ref: ${{ matrix.branch }}
          persist-credentials: false
      - uses: ruby/setup-ruby@b90be12699fdfcbee4440c2bba85f6f460446bb0 # v1.279.0
        with:
          ruby-version: 3.4
          bundler: none
      - name: Install libraries
        run: |
          set -x
          sudo apt-get update -q || :
          sudo apt-get install --no-install-recommends -q -y build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm-dev bison autoconf
      - name: Build Ruby
        run: |
          export GNUMAKEFLAGS="-j$((1 + $(nproc)))"
          ./autogen.sh
          ./configure -C --disable-install-doc
          make
        working-directory: ruby/ruby
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: rubygems/rubygems
          persist-credentials: false
        if: matrix.branch == 'ruby_3_4'
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: ruby/rubygems
          persist-credentials: false
        if: matrix.branch != 'ruby_3_4'
      - name: Sync tools
        run: |
          ruby tool/sync_default_gems.rb rubygems
          mv spec/bundler/support/bundle spec/bin/bundle # TODO: fix `sync_default_gems.rb` script so we don't need to vendor the ruby-core binstub ourselves
        working-directory: ruby/ruby
      - name: Test RubyGems
        run: make -s test-all TESTS="--no-retry -j$((1 + $(nproc)))"
        working-directory: ruby/ruby
        if: matrix.target == 'Rubygems'
      - name: Test Bundler
        run: |
          git add .
          make test-bundler-parallel
        working-directory: ruby/ruby
        if: matrix.target == 'Bundler'

  all-pass:
    name: All ruby-core jobs pass

    if: always()

    needs:
      - ruby_core

    runs-on: ubuntu-latest

    steps:
      - name: check dependent jobs
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
