name: Sync ruby
on:
  push:
    branches: [master]
jobs:
  sync:
    name: Sync ruby
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'ruby' }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Create GitHub App token
        id: app-token
        uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94 # v2.2.0
        with:
          app-id: 2060836
          private-key: ${{ secrets.RUBY_SYNC_DEFAULT_GEMS_PRIVATE_KEY }}
          owner: ruby
          repositories: ruby

      - name: Sync to ruby/ruby
        uses: convictional/trigger-workflow-and-wait@f69fa9eedd3c62a599220f4d5745230e237904be # v1.6.5
        with:
          owner: ruby
          repo: ruby
          workflow_file_name: sync_default_gems.yml
          github_token: ${{ steps.app-token.outputs.token }}
          ref: master
          client_payload: |
            {"gem":"${{ github.event.repository.name }}","before":"${{ github.event.before }}","after":"${{ github.event.after }}"}
          propagate_failure: true
          wait_interval: 10
