name: weekly-update

on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

permissions:
  contents: read

jobs:
  weekly_update:
    name: Rubygems weekly update
    runs-on: ${{ matrix.os }}
    if: github.repository == 'ruby/rubygems'
    strategy:
      matrix:
        os: [ubuntu-24.04]
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Config git
        run: |
          git config --global user.name "License Update"
          git config --global user.email license.update@rubygems.org
          git config --global push.autoSetupRemote true

      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: true

      - name: Check versions
        run: |
          ruby --version
          rake --version

      - name: Update SPDX license list
        run: |
          rake update_licenses_branch
          git diff --no-ext-diff --ignore-submodules --quiet "${BASE##*/}" -- || {
            git push origin
            gh pr create --base "${BASE##*/}" --fill --label "rubygems: enhancement"
          }
        env:
          BASE: ${{ github.ref }}
          GH_TOKEN: ${{ github.token }}
